name: Infra Deployment and Training

on:
  push:
    paths: 
      - '.github/workflows/setup.yml'
 
 
# CONFIGURATION 
#
# 1. Set up the following secrets in your repository: 
#   AZURE_RESOURCE_GROUP -
#   STORAGE_ACCOUNT 
env:
  AZURE_RESOURCE_GROUP: MLOpsGithubVal    #set this to your resource group name 
  #STORAGE_ACCOUNT: storage-account-name           #set this to your storage-account-name
    
jobs:
  deployment:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    # Login to Azure
    - name: Azure Login
      id: azure_login
      uses: github-actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
